spring.application.name=ProductManagementAppli
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
logging.level.org.springframework.jdbc.core=DEBUG
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false